### ISSUE TITLE
Issue Sending Pic Off IRCC

### ISSUE THREAD

**Issue by curtc757** [waynehaffenden/bravia#16]
First off Wayne, your module saved me an incredible amount of time. So Thank You! While working with the code found an issue that may be in your module or in the Sony itself - not sure. I've been working with JS and Node less than a month so what do I know?!  The code equivalent for the Picture Off (Pic Off) button on the remote isn't listed on Sony's developer site.  I retrieved all codes using the getRemoteControllerInfo though and came up two text options both having the same IRCC:  

{ name: 'PicOff', value: 'AAAAAQAAAAEAAAA+Aw==' }

 { name: 'PictureOff', value: 'AAAAAQAAAAEAAAA+Aw==' }

I thought that I would share with you and folks that may care that the only working option (for my Bravia anyway) is to use  bravia.send('PicOff');    Sending the code will not work and sending 'PictureOff' text will not work. This may vary by model.

Thanks again for your work.  Curt

**Comment by waynehaffenden** [comment]
@curtc757 Thank you for taking the time to write such kind feedback! Great find, it is an issue (feature?) with Sony as that method `getRemoteControllerInfo` is retrieved from the TVs internal API.

Thanks for sharing your find, this could save someone else a lot of time. I'll close it as it's not an open issue though, thanks again.
