### ISSUE TITLE
Sending multiple commands not working

### ISSUE THREAD

**Issue by phillipsnick** [waynehaffenden/bravia#2]
Following the example in the README, unable to get more than one command to fire.

```
bravia.send(['Up', 'Down', 'Left', 'Right']);
```

Not too sure how this was intended to work https://github.com/waynehaffenden/bravia/blob/master/src/bravia.js#L121

**Comment by waynehaffenden** [comment]
This should work now, clearly this wasn't ever tested properly by me :( I built this project for a friend as I don't actually own a Sony Bravia TV so keep me posted on anything you find =)
