### ISSUE TITLE
Fully Document API

### ISSUE THREAD

**Issue by waynehaffenden** [waynehaffenden/bravia#6]
Initially using the Wiki on this repository, document all the API protocols, versions, methods, parameters and responses using what we know and from contributions from others who have explored the API in more detail.

It may possibly make sense in the future based upon the poor documentation support from Sony to host an external Wiki website so that this documentation is not just associated with this module or implementation.

**Comment by JamesScammell** [comment]
@luisg1369 what are you struggling with?
